apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-go
  name: client-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-go
    spec:
      containers:
      - image: client-go:latest
        name: client-go
        imagePullPolicy: Never
        resources: {}
status: {}
